name: compilepaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      DIR: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pandoc
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            texlive texlive-latex-extra pandoc latexmk \
            texlive-bibtex-extra biber \
            texlive-fonts-recommended texlive-fonts-extra lmodern fonts-linuxlibertine \
            python3 python3-yaml \
            xz-utils make gpg-agent
          python3 -m pip install -r ${{ env.DIR }}/requirements.txt
      - name: pandoc compile
        working-directory: ${{ env.DIR }}
        run: make all
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/*.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF files
          path: ./github_artifacts
  deploy:
    needs: [paper]
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'CaptainSifff/paper_teaching-learning-RSE' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
